name: story_app
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  timeago: ^3.6.1
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/icon/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/Circular-Std.ttf
